In [3]:
import torch
import torch.nn.functional as F
from config import SA_config
from SA import LM
from utils import *

/home/nima/Documents/enviroments/pytorch/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
c = SA_config(embedding = 1000,n_layers = 25)

In [5]:
m = LM(c)

In [6]:
x = torch.randint(0, 9000, (3, 100))


In [17]:

for i in range(20):
    y = m(x)
    loss = F.cross_entropy(y.transpose(-1 ,-2), x)
    loss.backward()
    print(loss)

    for p in m.parameters():
        if p.grad != None:

            p.data -= 0.01 * p.grad

tensor(9.4237, grad_fn=<NllLoss2DBackward0>)
tensor(8.4607, grad_fn=<NllLoss2DBackward0>)
tensor(7.1984, grad_fn=<NllLoss2DBackward0>)
tensor(5.6777, grad_fn=<NllLoss2DBackward0>)
tensor(3.9957, grad_fn=<NllLoss2DBackward0>)
tensor(2.3083, grad_fn=<NllLoss2DBackward0>)
tensor(0.9113, grad_fn=<NllLoss2DBackward0>)
tensor(0.2087, grad_fn=<NllLoss2DBackward0>)
tensor(0.0324, grad_fn=<NllLoss2DBackward0>)
tensor(0.0048, grad_fn=<NllLoss2DBackward0>)
tensor(0.0007, grad_fn=<NllLoss2DBackward0>)
tensor(0.0001, grad_fn=<NllLoss2DBackward0>)
tensor(1.9576e-05, grad_fn=<NllLoss2DBackward0>)
tensor(4.1509e-06, grad_fn=<NllLoss2DBackward0>)
tensor(1.0065e-06, grad_fn=<NllLoss2DBackward0>)
tensor(2.8054e-07, grad_fn=<NllLoss2DBackward0>)
tensor(8.6625e-08, grad_fn=<NllLoss2DBackward0>)
tensor(2.2650e-08, grad_fn=<NllLoss2DBackward0>)
tensor(5.9605e-09, grad_fn=<NllLoss2DBackward0>)
tensor(1.1921e-09, grad_fn=<NllLoss2DBackward0>)


In [14]:
type(None)

NoneType

In [16]:
for i in m.named_parameters():
    if i[1].grad == None:
        print(i)

('lm_engine.pe.weight', Parameter containing:
tensor([[ 0.2930, -0.6338, -1.5712,  ...,  0.9920, -0.9126,  0.1010],
        [-0.3452, -1.3622,  0.2309,  ...,  0.8620,  1.1642, -0.6288],
        [ 0.2144, -0.9221, -0.8013,  ..., -0.4311,  0.3841,  1.5175],
        ...,
        [ 0.6759,  0.6728, -0.6397,  ...,  0.0703,  1.3277, -0.7697],
        [ 0.0762, -0.6548, -1.3432,  ..., -0.1528, -1.4745, -0.3874],
        [ 0.4592, -2.0002, -0.5044,  ...,  0.4784, -0.2631, -0.2801]],
       requires_grad=True))


In [9]:
list(m.parameters())

[Parameter containing:
 tensor([[-1.6217, -0.5215, -1.7193,  ..., -1.6943,  0.3304,  0.9720],
         [-0.7217,  0.9452,  0.9164,  ...,  0.1248,  0.1964, -0.9854],
         [-0.3474, -0.0580,  1.5149,  ...,  0.3281,  0.2605,  0.6630],
         ...,
         [-0.8010, -0.6080,  0.1468,  ...,  0.8698,  1.0526,  1.4314],
         [ 0.3230,  1.2253, -1.2784,  ..., -0.4665,  1.5726,  1.2044],
         [ 1.1645, -0.3257, -0.4895,  ...,  0.7243,  0.9565, -2.2280]],
        requires_grad=True),
 Parameter containing:
 tensor([[ 0.2930, -0.6338, -1.5712,  ...,  0.9920, -0.9126,  0.1010],
         [-0.3452, -1.3622,  0.2309,  ...,  0.8620,  1.1642, -0.6288],
         [ 0.2144, -0.9221, -0.8013,  ..., -0.4311,  0.3841,  1.5175],
         ...,
         [ 0.6759,  0.6728, -0.6397,  ...,  0.0703,  1.3277, -0.7697],
         [ 0.0762, -0.6548, -1.3432,  ..., -0.1528, -1.4745, -0.3874],
         [ 0.4592, -2.0002, -0.5044,  ...,  0.4784, -0.2631, -0.2801]],
        requires_grad=True),
 Parameter con